name: bima

services:
  postgres:
    image: postgres
    container_name: bima-postgres
    environment:
      POSTGRES_DB: bima
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"
    volumes:
      - bima_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  bima_postgres_data:
